return {
 	[1] = "app/Project/main";
 	[2] = "app/View/main";
 	[3] = "app/Show/main";
 	[4] = "app/Select/main";
 	[5] = "app/Edit/main";
 	[6] = "app/Snap/main";
 	[7] = "app/Assistant/main";
 	[8] = "app/Graphics/main";
 	[9] = "app/Steel/main";
 	[10] = "app/Contacts/main";
 	[11] = "app/Msg/main";
 	[12] = "app/Appendix/main";
 	[13] = "app/Model/main";
 	[14] = "app/Develop/main";
 	[15] = "app/Tekla/main";
 	[16] = "app/Configure/main";
 	[17] = "app/DXF/main";
 	[18] = "app/SelectJoint/main";
 	[19] = "app/toolbar/main";
};
